version: '3'
services:
  web:
    &web
    build: ./web
    image: pdfrenderer/web
    restart: always
    command: ./start.sh
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./web/.env
      - ./db/.env
    volumes:
      - static_volume:/home/docker/code/static
      - media_volume:/home/docker/code/media

  nginx:
    image: nginx:1.15.7
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web

  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    volumes:
      - db_volume:/var/lib/mysql
    env_file:
      - ./db/.env

  redis:
    image: redis:5.0

  celeryworker:
    <<: *web
    image: pdfrenderer/celeryworker
    command: ./celery/worker/start.sh

  celerybeat:
    <<: *web
    image: pdfrenderer/celerybeat
    command: ./celery/beat/start.sh

  flower:
    <<: *web
    image: pdfrenderer/flower
    ports:
      - "5555:5555"
    command: ./celery/flower/start.sh

volumes:
  db_volume:
  static_volume:
  media_volume:
